-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 11:34:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BubbleGum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BubbleGum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BubbleGum` DEFAULT CHARACTER SET utf8 ;
USE `BubbleGum` ;

-- -----------------------------------------------------
-- Table `BubbleGum`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`Chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_bubble` BIT NOT NULL,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `sent_at` BIGINT NOT NULL,
  `sent_by_user` INT NOT NULL,
  `sent_in_chat` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Nachricht_User_idx` (`sent_by_user` ASC)  ,
  INDEX `fk_Nachricht_Chat1_idx` (`sent_in_chat` ASC)  ,
  CONSTRAINT `fk_Nachricht_User`
    FOREIGN KEY (`sent_by_user`)
    REFERENCES `BubbleGum`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nachricht_Chat1`
    FOREIGN KEY (`sent_in_chat`)
    REFERENCES `BubbleGum`.`Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`User_in_Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`User_in_Chat` (
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  `is_admin` BIT NOT NULL,
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_User_has_Chat_Chat1_idx` (`chat_id` ASC)  ,
  INDEX `fk_User_has_Chat_User1_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_user_has_chat_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `BubbleGum`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_chat_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `BubbleGum`.`Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`Invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`Invite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_accepted` BIT NOT NULL,
  `sent_by_user` INT NOT NULL,
  `for_chat` INT NOT NULL,
  `invited_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Einladung_User_in_Chat1_idx` (`sent_by_user` ASC, `for_chat` ASC)  ,
  INDEX `fk_Einladung_User1_idx` (`invited_user` ASC)  ,
  CONSTRAINT `fk_Einladung_User_in_Chat1`
    FOREIGN KEY (`sent_by_user` , `for_chat`)
    REFERENCES `BubbleGum`.`User_in_Chat` (`user_id` , `chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Einladung_User1`
    FOREIGN KEY (`invited_user`)
    REFERENCES `BubbleGum`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`User_read_Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`User_read_Message` (
  `user_id` INT NOT NULL,
  `message_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `message_id`),
  INDEX `fk_User_has_Message_Message1_idx` (`message_id` ASC)  ,
  INDEX `fk_User_has_Message_User1_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_User_has_Message_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `BubbleGum`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Message_Message1`
    FOREIGN KEY (`message_id`)
    REFERENCES `BubbleGum`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BubbleGum`.`Conversation_access_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BubbleGum`.`Conversation_access_key` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  `creation_date` BIGINT NOT NULL,
  `hash` VARCHAR(45) NOT NULL,
  INDEX `fk_User_has_Chat_Chat2_idx` (`chat_id` ASC)  ,
  INDEX `fk_User_has_Chat_User2_idx` (`user_id` ASC)  ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_has_Chat_User2`
    FOREIGN KEY (`user_id`)
    REFERENCES `BubbleGum`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Chat_Chat2`
    FOREIGN KEY (`chat_id`)
    REFERENCES `BubbleGum`.`Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
